#!/usr/bin/bash

set -euo pipefail

# Get the tools we need to add additional APT sources.
apt-get install -y --no-install-recommends \
    apt-transport-https \
    ca-certificates \
    curl \
    gpg \
    lsb-release

# Make a place to store our keyrings.
mkdir -p /usr/local/share/keyrings
