#!/usr/bin/bash

set -euo pipefail

RUST_PROFILE=default
RUST_VERSION=1.89.0

export CARGO_HOME=/usr/local/cargo
export RUSTUP_HOME=/usr/local/rustup

cat > /usr/local/etc/environment.d/20-rust <<EOF
export CARGO_HOME=$CARGO_HOME
export RUSTUP_HOME=$RUSTUP_HOME

PATH="$CARGO_HOME/bin:\$PATH"
EOF

sudo mkdir -p ${CARGO_HOME}
sudo chown ${USERNAME}:${USERNAME} ${CARGO_HOME}

sudo mkdir -p ${RUSTUP_HOME}
sudo chown ${USERNAME}:${USERNAME} ${RUSTUP_HOME}

sudo apt-get install -y --no-install-recommends \
    rustup

rustup toolchain install \
    --no-self-update \
    --profile ${RUST_PROFILE} \
    ${RUST_VERSION}

rustup component add \
  clippy \
  rust-analyzer \
  rust-src \
  rustfmt
