#!/usr/bin/bash

set -euo pipefail

WORK_DIR="$(mktemp -d)"
pushd "${WORK_DIR}"

DENO_VERSION=1.45.3
DENO_ARCH=$(uname -m)

curl -fsSL https://github.com/denoland/deno/releases/download/v${DENO_VERSION}/deno-${DENO_ARCH}-unknown-linux-gnu.zip \
    --output deno.zip

unzip deno.zip
chmod 755 deno
sudo mv deno /usr/local/bin/deno

popd
rm -rf "${WORK_DIR}"
