#!/usr/bin/bash

set -euo pipefail

# Based on https://github.com/adoptium/containers/blob/main/24/jdk/ubuntu/noble/Dockerfile

WORK_DIR="$(mktemp -d)"
pushd "${WORK_DIR}"

JAVA_HOME=/usr/local/openjdk
JAVA_VERSION=24.0.2+12
JAVA_SHA256_SUM='6f8725d186d05c627176db9c46c732a6ef3ba41d9e9b3775c4727fc8ac642bb2'

cat > /usr/local/etc/environment.d/30-java <<EOF
export JAVA_HOME=$JAVA_HOME

PATH="$JAVA_HOME/bin:\$PATH"
EOF

JAVA_BINARY_URL="https://github.com/adoptium/temurin24-binaries/releases/download"
JAVA_BINARY_URL="${JAVA_BINARY_URL}/jdk-$(echo ${JAVA_VERSION} | jq -Rr @uri)"
JAVA_BINARY_URL="${JAVA_BINARY_URL}/OpenJDK24U-jdk_aarch64_linux_hotspot"
JAVA_BINARY_URL="${JAVA_BINARY_URL}_$(echo ${JAVA_VERSION} | sed -e 's/+/_/').tar.gz"

echo Downloading OpenJDK ${JAVA_VERSION} from ${JAVA_BINARY_URL}

curl -fsSL ${JAVA_BINARY_URL} --output openjdk.tar.gz

echo "${JAVA_SHA256_SUM} *${WORK_DIR}/openjdk.tar.gz" | sha256sum -c -

sudo mkdir -p "$JAVA_HOME"
sudo tar \
    --extract \
    --file ${WORK_DIR}/openjdk.tar.gz \
    --directory "${JAVA_HOME}" \
    --strip-components 1 \
    --no-same-owner \

popd
rm -rf "${WORK_DIR}"
