#!/usr/bin/bash

set -euo pipefail

# Based on https://github.com/adoptium/containers/blob/main/21/jdk/ubuntu/jammy/Dockerfile

WORK_DIR="$(mktemp -d)"
pushd "${WORK_DIR}"

JAVA_HOME=/usr/local/openjdk
JAVA_VERSION=21.0.4+7

case "$(uname -m)" in
    aarch64|arm64)
        JAVA_SHA256_SUM='d768eecddd7a515711659e02caef8516b7b7177fa34880a56398fd9822593a79'
        JAVA_ARCH='aarch64'
        ;;
    x64|x86_64|amd64)
        JAVA_SHA256_SUM='51fb4d03a4429c39d397d3a03a779077159317616550e4e71624c9843083e7b9'
        JAVA_ARCH='x64'
        ;;
esac;

JAVA_BINARY_URL="https://github.com/adoptium/temurin21-binaries/releases/download"
JAVA_BINARY_URL="${JAVA_BINARY_URL}/jdk-$(echo ${JAVA_VERSION} | jq -Rr @uri)"
JAVA_BINARY_URL="${JAVA_BINARY_URL}/OpenJDK21U-jdk_${JAVA_ARCH}_linux_hotspot"
JAVA_BINARY_URL="${JAVA_BINARY_URL}_$(echo ${JAVA_VERSION} | sed -e 's/+/_/').tar.gz"

curl -fsSL ${JAVA_BINARY_URL} --output openjdk.tar.gz

echo "${JAVA_SHA256_SUM} *${WORK_DIR}/openjdk.tar.gz" | sha256sum -c -

sudo mkdir -p "$JAVA_HOME"
sudo tar \
    --extract \
    --file ${WORK_DIR}/openjdk.tar.gz \
    --directory "${JAVA_HOME}" \
    --strip-components 1 \
    --no-same-owner \

popd
rm -rf "${WORK_DIR}"
