#!/usr/bin/bash

set -euo pipefail

WORK_DIR="$(mktemp -d)"
pushd "${WORK_DIR}"

MAVEN_HOME=/usr/local/maven
MAVEN_VERSION=3.9.11
MAVEN_SHA512_SUM=bcfe4fe305c962ace56ac7b5fc7a08b87d5abd8b7e89027ab251069faebee516b0ded8961445d6d91ec1985dfe30f8153268843c89aa392733d1a3ec956c9978

cat > /usr/local/etc/environment.d/31-maven <<EOF
export MAVEN_HOME=$MAVEN_HOME

PATH="$MAVEN_HOME/bin:\$PATH"
EOF

curl -fsSL https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    --output maven.tar.gz

echo "${MAVEN_SHA512_SUM} *${WORK_DIR}/maven.tar.gz" | sha512sum -c -

sudo mkdir -p "$MAVEN_HOME"
sudo tar \
    --extract \
    --file ${WORK_DIR}/maven.tar.gz \
    --directory "${MAVEN_HOME}" \
    --strip-components 1 \
    --no-same-owner \

popd
rm -rf "${WORK_DIR}"
