#!/usr/bin/bash

set -euo pipefail

WORK_DIR="$(mktemp -d)"
pushd "${WORK_DIR}"

MAVEN_HOME=/usr/local/maven
MAVEN_VERSION=3.9.8
MAVEN_SHA512_SUM=7d171def9b85846bf757a2cec94b7529371068a0670df14682447224e57983528e97a6d1b850327e4ca02b139abaab7fcb93c4315119e6f0ffb3f0cbc0d0b9a2

curl -fsSL https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    --output maven.tar.gz

echo "${MAVEN_SHA512_SUM} *${WORK_DIR}/maven.tar.gz" | sha512sum -c -

sudo mkdir -p "$MAVEN_HOME"
sudo tar \
    --extract \
    --file ${WORK_DIR}/maven.tar.gz \
    --directory "${MAVEN_HOME}" \
    --strip-components 1 \
    --no-same-owner \

popd
rm -rf "${WORK_DIR}"
