#!/usr/bin/bash

set -euo pipefail

WORK_DIR="$(mktemp -d)"
pushd "${WORK_DIR}"

SWIFT_VERSION=5.10.1

SWIFT_HOME=/usr/local/swift

cat > /usr/local/etc/environment.d/50-swift <<EOF
PATH="$SWIFT_HOME/bin:\$PATH"
EOF

# Based on https://www.swift.org/install/linux/tarball/

# 1. Install required dependencies:

sudo apt-get install -y --no-install-recommends \
    binutils \
    git \
    gnupg2 \
    libc6-dev \
    libcurl4-openssl-dev \
    libedit2 \
    libgcc-13-dev \
    libncurses-dev \
    libpython3-dev \
    libsqlite3-0 \
    libstdc++-13-dev \
    libxml2-dev \
    libz3-dev \
    pkg-config \
    tzdata \
    unzip \
    zlib1g-dev

# 2. Download the appropriate binary release:

case "$(uname -m)" in
    aarch64|arm64)
        SWIFT_ARCH_SUFFIX='-aarch64'
        ;;
    x64|x86_64|amd64)
        SWIFT_ARCH_SUFFIX=''
        ;;
esac;


SWIFT_WEBDIR="https://download.swift.org/swift-${SWIFT_VERSION}-release/ubuntu2404${SWIFT_ARCH_SUFFIX}/swift-${SWIFT_VERSION}-RELEASE"
SWIFT_BIN_URL="${SWIFT_WEBDIR}/swift-${SWIFT_VERSION}-RELEASE-ubuntu24.04${SWIFT_ARCH_SUFFIX}.tar.gz"
SWIFT_SIG_URL="${SWIFT_WEBDIR}/swift-${SWIFT_VERSION}-RELEASE-ubuntu24.04${SWIFT_ARCH_SUFFIX}.tar.gz.sig"

curl -fsSL "$SWIFT_BIN_URL" -o swift.tar.gz "$SWIFT_SIG_URL" -o swift.tar.gz.sig

# 3. Import and verify the PGP signature:

SWIFT_SIGNING_KEY=A62AE125BBBFBB96A6E042EC925CC1CCED3D1561

export GNUPGHOME="${WORK_DIR}"

gpg \
    --quiet \
    --keyserver hkp://keyserver.ubuntu.com \
    --recv-keys ${SWIFT_SIGNING_KEY}

gpg --verify swift.tar.gz.sig

# 4. Extract the archive:
sudo mkdir -p ${SWIFT_HOME}

sudo tar \
    --extract \
    --gunzip \
    --file swift.tar.gz \
    --strip-components 2 \
    --directory ${SWIFT_HOME}
